kind: pipeline
name: node.v11
steps:
steps:
- name: mariadb & node test
  image: docker
  image: docker:dind
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
  - docker pull nodejs/node:11
  - npm run mariadb

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
