kind: pipeline
name: node.v11
steps:
- name: test
  image: node:11
  commands:
  - sleep 15
  - npm install
  - npm run lint
  - npm run test:drone
  #- npm run codecov:upload

- name: codecov
  image: plugins/codecov
  settings:
    token:
      from_secret: CODECOV_TOKEN

services:
- name: drone.mariadb
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: mysql
