language: node_js

node_js:
  - "11"
  - "10"
  - "8"
  - "6"

# services:
#   - docker

before_script:
  - sudo /etc/init.d/mysql stop # - sudo systemctl stop mysql
  - npm run mariadb
  - npm install -g codecov

script:
  - npm run lint
  - npm test

#after_script:
#  - npm run codecov:ci
after_success:
  - npm run codecov:ci

notifications:
  email:
    on_success: never
    on_failure: always