name: Setup Build Test Publish
on: 
  - push
  - pull_request
jobs:
  setup_build_test_publish:
    runs-on: ubuntu-latest
    steps:
      # - name: Stop the Default MySQL
      #   run: sudo systemctl stop mysql
      - name: Start MariaDB/MySQL server
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: 'latest'
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_general_ci'
        env:
          MYSQL_DATABASE: 'mysql'
          MYSQL_ALLOW_EMPTY_PASSWORD: true

      - uses: actions/checkout@v2
      - name: Setup, Run Tests and Generate coverage report, then publish
        run: |
          npm version
          npm install
          npm test
          npm config set //npm.pkg.github.com/:_authToken $TOKEN
          npm publish --access public
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
